spring.application.name=InterfaceApp

server.port=7072

# Kafka Configuration
# ===============
#For Local System
spring.kafka.bootstrap-servers=localhost:7092,localhost:7093
#For Containers
#spring.kafka.bootstrap-servers=kafkaECommerce1:27092,kafkaECommerce2:27092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.trusted.packages=*

# Consumer
spring.kafka.consumer.group-id=library-inventory-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.glory.global.dto.BorrowResponseDTO
# ===============